/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_human_interface_device         9
#define gattdb_protocol_mode                  11
#define gattdb_report                         13
#define gattdb_report_reference               14
#define gattdb_report_map                     16
#define gattdb_external_report_reference      17
#define gattdb_hid_information                19
#define gattdb_hid_control_point              22
#define gattdb_device_name                    25
#define gattdb_device_information             28
#define gattdb_manufacturer_name_string       30
#define gattdb_model_number_string            32
#define gattdb_hardware_revision_string       34
#define gattdb_firmware_revision_string       36
#define gattdb_system_id                      38
#define gattdb_pnp_id_0                       40
#define gattdb_scan_parameters                41
#define gattdb_scan_interval_window           43
#define gattdb_scan_refresh                   45
#define gattdb_battery_service_0              47
#define gattdb_battery_level                  49
#define gattdb_characteristic_presentation_format 50


#endif // __GATT_DB_H
